# Generated by Django 4.2.7 on 2023-12-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
