# Generated by Django 4.2.7 on 2023-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
