# Generated by Django 4.2.7 on 2023-12-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_cart_product_remove_cart_user_delete_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
