# Generated by Django 4.2.7 on 2023-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_coupon_wishlist_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
