# Generated by Django 4.2.7 on 2023-12-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_discounted_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='device',
        ),
    ]
