# Generated by Django 4.2.7 on 2024-01-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
