# Generated by Django 4.2.7 on 2024-01-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_product_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='product_offer',
        ),
    ]
