# Generated by Django 4.2.7 on 2024-01-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_discounted_price_product_product_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_offer',
            new_name='offer_price',
        ),
    ]
