# Generated by Django 4.2.7 on 2024-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
