# Generated by Django 4.2.7 on 2023-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
