# Generated by Django 4.2.7 on 2023-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
