# Generated by Django 4.2.7 on 2023-12-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
